backend:
  name: git-gateway
  repo: BountyGA/whatsapp-store
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
